from enum import StrEnum


class ReasonCode(StrEnum):
    POSITIVE_RAW_EV = "POSITIVE_RAW_EV"
    POSITIVE_RISK_ADJUSTED_EV = "POSITIVE_RISK_ADJUSTED_EV"
    BEST_CROSS_MARKET_VALUE = "BEST_CROSS_MARKET_VALUE"
    NO_POSITIVE_EDGE = "NO_POSITIVE_EDGE"
    BELOW_WATCH_THRESHOLD = "BELOW_WATCH_THRESHOLD"
    INVALID_ODDS = "INVALID_ODDS"
    INVALID_PROBABILITY = "INVALID_PROBABILITY"
    INCOMPLETE_MARKET_GROUP = "INCOMPLETE_MARKET_GROUP"
    NON_EXCLUSIVE_MARKET_GROUP = "NON_EXCLUSIVE_MARKET_GROUP"
    MIXED_FIXTURE_GROUP = "MIXED_FIXTURE_GROUP"
    MIXED_MARKET_GROUP = "MIXED_MARKET_GROUP"
    MIXED_LINE_GROUP = "MIXED_LINE_GROUP"
    STALE_MARKET_DATA = "STALE_MARKET_DATA"
    UNVERIFIED_MARKET_DATA = "UNVERIFIED_MARKET_DATA"
    UNSUPPORTED_SETTLEMENT_MODEL = "UNSUPPORTED_SETTLEMENT_MODEL"
    PHASE1_RATING_CAP = "PHASE1_RATING_CAP"
    PHASE1_EXECUTION_DISABLED = "PHASE1_EXECUTION_DISABLED"
    PENALTY_EXCEEDS_RAW_EDGE = "PENALTY_EXCEEDS_RAW_EDGE"
